version: '3.4'

services:
  php:
    build:
      context: .
      target: sylius_highest_order_shipment_tax_rate_plugin_php
      network: host
      args:
        - PRIVATE_FLEX=${PRIVATE_FLEX:-false}
    image: ghcr.io/nedac-sorbo/sylius_highest_order_shipment_tax_rate_plugin_php:latest
    environment:
      - APP_ENV=test
      - DATABASE_URL=mysql://sylius:highest_order_shipment_tax_rate@127.0.0.1:3306/sylius_highest_order_shipment_tax_rate
    volumes:
      # TODO: Mount templates/folders
      - .:/srv/sylius/vendor/nedac/sylius-highest-order-shipment-tax-rate-plugin
      - ./etc/build:/srv/sylius/etc/build
      - public:/srv/sylius/public:rw
      - public-media:/srv/sylius/public/media:rw
    network_mode: host

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sylius_highest_order_shipment_tax_rate
      - MYSQL_USER=sylius
      - MYSQL_PASSWORD=highest_order_shipment_tax_rate
    network_mode: host

  nginx:
    build:
      context: .
      target: sylius_highest_order_shipment_tax_rate_plugin_nginx
      network: host
      args:
        - PRIVATE_FLEX=${PRIVATE_FLEX:-false}
    image: ghcr.io/nedac-sorbo/sylius_highest_order_shipment_tax_rate_plugin_nginx:latest
    volumes:
      - public:/srv/sylius/public:ro
      - public-media:/srv/sylius/public/media:ro,nocopy
    network_mode: host

  nodejs:
    build:
      context: .
      target: sylius_highest_order_shipment_tax_rate_plugin_nodejs
      network: host
      args:
        - PRIVATE_FLEX=${PRIVATE_FLEX:-false}
    image: ghcr.io/nedac-sorbo/sylius_highest_order_shipment_tax_rate_plugin_nodejs:latest
    volumes:
      - ./src/Resources/public:/srv/sylius/vendor/nedac/sylius-highest-order-shipment-tax-rate-plugin/src/Resources/public
    network_mode: host

  chrome:
    build:
      context: .
      target: sylius_highest_order_shipment_tax_rate_plugin_chrome
      network: host
      args:
        - PRIVATE_FLEX=${PRIVATE_FLEX:-false}
    image: ghcr.io/nedac-sorbo/sylius_highest_order_shipment_tax_rate_plugin_chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    network_mode: host

volumes:
  public:
  public-media:
