name: default

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
      - name: Pull container images
        run: docker-compose pull || true
      - name: Build and start containers
        run: docker-compose up -d --build
      - name: Push container images
        run: |
          docker-compose push php && \
          docker-compose push nginx && \
          docker-compose push nodejs && \
          docker-compose push chrome
      - name: Install sub dependencies
        run: docker-compose exec -T php sh -c "(cd vendor/nedac/sylius-highest-order-shipment-tax-rate-plugin && composer install)"
      - name: Install phpcpd
        run: docker-compose exec -T php phive install --trust-gpg-keys 4AA394086372C20A phpcpd
      - name: Code duplication
        run: docker-compose exec -T php ./tools/phpcpd vendor/nedac/sylius-highest-order-shipment-tax-rate-plugin/src/ --fuzzy
      - name: Code style
        run: docker-compose exec -T php sh -c "(cd vendor/nedac/sylius-highest-order-shipment-tax-rate-plugin && vendor/bin/phpcs)"
      - name: Static analysis
        run: docker-compose exec -T php sh -c "(cd vendor/nedac/sylius-highest-order-shipment-tax-rate-plugin && vendor/bin/phpstan analyse src/ tests/ --level max)"
      - name: Spec tests
        run: docker-compose exec -T php sh -c "(cd vendor/nedac/sylius-highest-order-shipment-tax-rate-plugin && vendor/bin/phpspec run)"
      - name: Unit tests
        run: docker-compose exec -T php sh -c "(cd vendor/nedac/sylius-highest-order-shipment-tax-rate-plugin && vendor/bin/phpunit --testdox)"
      - name: Install twigcs
        run: docker-compose exec -T php composer global require friendsoftwig/twigcs
      - name: Template style
        run: docker-compose exec -T php twigcs vendor/nedac/sylius-highest-order-shipment-tax-rate-plugin/src/Resources/views --severity error
      - name: Create database schema
        run: docker-compose exec -T php bin/console doctrine:schema:create
      - name: End to end tests
        run: docker-compose exec -T php vendor/bin/behat
